import {app} from 'electron';
import {ChildProcessWithoutNullStreams,spawn} from 'node:child_process';
import fs from 'node:fs';import path from 'node:path';import readline from 'node:readline';
import {Client} from '@xhayper/discord-rpc';import {PresenceBackend,PresencePayload} from '../shared/types';import {encodeBridgeCommand,setPresenceCommand} from './discord-protocol';
type Connection='connecting'|'connected'|'disconnected'|'error';type Reporter=(status:Connection,error?:string,backend?:PresenceBackend)=>void;
interface PresenceTransport{readonly backend:PresenceBackend;connect(id:string,payload:()=>PresencePayload):Promise<void>;update(payload:PresencePayload):Promise<void>;clear():Promise<void>;stop():void;}
export function socialBridgePath():string{if(app.isPackaged)return path.join(process.resourcesPath,'native','discord-presence-bridge.exe');const ninja=path.join(app.getAppPath(),'native','discord-presence-bridge','build-ninja','discord-presence-bridge.exe');return fs.existsSync(ninja)?ninja:path.join(app.getAppPath(),'native','discord-presence-bridge','build','Release','discord-presence-bridge.exe');}
export class SocialSdkPresenceTransport implements PresenceTransport{
 readonly backend='discord-social-sdk' as const;private child:ChildProcessWithoutNullStreams|null=null;private applicationId='';private last='';constructor(private report:Reporter,private executable=socialBridgePath()){}
 async connect(id:string,payload:()=>PresencePayload):Promise<void>{if(!fs.existsSync(this.executable))throw new Error(`Discord Social SDK bridge not found: ${this.executable}`);this.applicationId=id;this.report('connecting',undefined,this.backend);await new Promise<void>((resolve,reject)=>{let settled=false;const child=spawn(this.executable,[],{stdio:['pipe','pipe','pipe'],windowsHide:true});this.child=child;const fail=(error:Error)=>{if(settled)return;settled=true;clearTimeout(timeout);this.child=null;child.kill();reject(error);};const timeout=setTimeout(()=>fail(new Error('Discord Social SDK bridge startup timed out')),5000);child.once('error',fail);child.once('exit',code=>{this.child=null;if(!settled)fail(new Error(`Discord Social SDK bridge exited during startup (${code??'unknown'})`));else this.report('disconnected','Discord Social SDK bridge stopped',this.backend);});readline.createInterface({input:child.stdout}).on('line',line=>{try{const event=JSON.parse(line) as {type?:string;status?:string;message?:string};if(event.type==='status'&&event.status==='connected'&&!settled){settled=true;clearTimeout(timeout);this.report('connected',undefined,this.backend);resolve();}else if(event.type==='error')this.report('error',event.message??'Discord Social SDK error',this.backend);}catch{this.report('error','Malformed response from Discord Social SDK bridge',this.backend);}});child.stderr.on('data',()=>this.report('error','Discord Social SDK bridge reported an internal error',this.backend));});await this.update(payload());}
 async update(payload:PresencePayload):Promise<void>{const key=JSON.stringify(payload);if(!this.child||key===this.last)return;this.last=key;this.child.stdin.write(encodeBridgeCommand(setPresenceCommand(this.applicationId,payload)));}
 async clear():Promise<void>{if(!this.child||!this.last)return;this.last='';this.child.stdin.write(encodeBridgeCommand({type:'clearPresence'}));}
 stop():void{const child=this.child;this.child=null;this.last='';if(child&&!child.killed){child.stdin.write(encodeBridgeCommand({type:'clearPresence'}));child.stdin.write(encodeBridgeCommand({type:'shutdown'}));setTimeout(()=>{if(!child.killed)child.kill();},1500).unref();}}
}
export class LegacyRpcPresenceTransport implements PresenceTransport{readonly backend='legacy-rpc' as const;private client:Client|null=null;private last='';constructor(private report:Reporter){}async connect(id:string,payload:()=>PresencePayload):Promise<void>{this.report('connecting',undefined,this.backend);const client=new Client({clientId:id});this.client=client;client.on('ready',()=>{this.report('connected',undefined,this.backend);void this.update(payload());});client.on('disconnected',()=>this.report('disconnected',undefined,this.backend));await client.login();}async update(payload:PresencePayload):Promise<void>{const key=JSON.stringify(payload);if(!this.client?.user||key===this.last)return;this.last=key;await this.client.user.setActivity(payload);}async clear():Promise<void>{if(!this.client?.user||!this.last)return;this.last='';await this.client.user.clearActivity();}stop():void{this.client?.destroy();this.client=null;this.last='';}}
export class DiscordService{private transport:PresenceTransport|null=null;private timer:NodeJS.Timeout|null=null;private attempts=0;constructor(private report:Reporter){}async connect(id:string,payload:()=>PresencePayload):Promise<void>{this.stop();if(!id){this.report('error','Add a Discord Application Client ID to connect.','none');return;}try{const social=new SocialSdkPresenceTransport(this.report);await social.connect(id,payload);this.transport=social;this.attempts=0;return;}catch(error){this.report('connecting',`Social SDK unavailable; using legacy RPC (${error instanceof Error?error.message:'startup failure'})`,'legacy-rpc');}try{const legacy=new LegacyRpcPresenceTransport(this.report);this.transport=legacy;await legacy.connect(id,payload);this.attempts=0;}catch(error){this.report('error',error instanceof Error?error.message:'Discord RPC unavailable','legacy-rpc');this.retry(id,payload);}}async update(payload:PresencePayload):Promise<void>{try{await this.transport?.update(payload);}catch{this.report('disconnected','Presence update failed',this.transport?.backend??'none');}}async clear():Promise<void>{try{await this.transport?.clear();}catch{this.report('disconnected','Could not clear presence',this.transport?.backend??'none');}}stop():void{if(this.timer)clearTimeout(this.timer);this.timer=null;this.transport?.stop();this.transport=null;}private retry(id:string,payload:()=>PresencePayload){if(this.timer)return;const delay=Math.min(60_000,2000*2**this.attempts++);this.timer=setTimeout(()=>{this.timer=null;void this.connect(id,payload);},delay);}}
