import {app} from 'electron'; import fs from 'node:fs'; import path from 'node:path'; import {z} from 'zod'; import {activities,Settings,SettingsPatch} from '../shared/types';
export const DISCORD_APPLICATION_ID='1525666267770650674';
const defaultProfile={id:'default',name:'Default',icon:'D',customStatus:'',manualActivity:null,privateProject:true,showProject:false,showBranch:false} as const;
export const defaults:Settings={enabled:false,showProject:false,privateProject:true,hiddenProjectIds:[],showBranch:false,showModel:false,showActivity:true,showElapsed:true,autoDetect:true,launchAtStartup:false,idleTimeoutMinutes:15,manualActivity:null,customStatus:'',automaticStatusTemplate:'{action} in {project}',manualProject:'',discordClientId:DISCORD_APPLICATION_ID,activeProfileId:'default',presenceRules:[],projectStatusTemplates:[],theme:'midnight',accentColor:'#7c78ff',systemIconBackground:'#f97316',largeImageKey:'codex',largeImageText:'Codex',smallImageKey:'',smallImageText:'',profiles:[defaultProfile,{id:'focus',name:'Focus',icon:'F',customStatus:'Deep work',manualActivity:'Coding',privateProject:true,showProject:false,showBranch:false},{id:'public',name:'Public build',icon:'P',customStatus:'Building with Codex',manualActivity:null,privateProject:false,showProject:true,showBranch:false},{id:'stealth',name:'Stealth',icon:'S',customStatus:'Working in Codex',manualActivity:null,privateProject:true,showProject:false,showBranch:false}]};
const profile=z.object({id:z.string().regex(/^[a-z0-9-]{1,24}$/),name:z.string().min(1).max(24),icon:z.string().min(1).max(2),customStatus:z.string().max(64),manualActivity:z.enum(activities).nullable(),privateProject:z.boolean(),showProject:z.boolean(),showBranch:z.boolean()});
const ruleCondition=z.object({activities:z.array(z.enum(activities)).max(activities.length).optional(),projectIds:z.array(z.string().regex(/^[a-f0-9]{16}$/)).max(100).optional(),daysOfWeek:z.array(z.number().int().min(0).max(6)).max(7).optional(),startMinute:z.number().int().min(0).max(1439).optional(),endMinute:z.number().int().min(0).max(1439).optional()});
const ruleAction=z.object({customStatus:z.string().max(64).optional(),activity:z.enum(activities).optional(),hidePresence:z.boolean().optional(),privateProject:z.boolean().optional(),showProject:z.boolean().optional(),showBranch:z.boolean().optional()});
const presenceRule=z.object({id:z.string().regex(/^[a-z0-9-]{1,64}$/),name:z.string().min(1).max(48),enabled:z.boolean(),condition:ruleCondition,action:ruleAction});
const projectTemplate=z.object({projectId:z.string().regex(/^[a-f0-9]{16}$/),status:z.string().min(1).max(64)});
const assetKey=z.string().regex(/^[a-zA-Z0-9_-]{0,64}$/);const assetText=z.string().max(128);
const schema=z.object({enabled:z.boolean(),showProject:z.boolean(),privateProject:z.boolean(),hiddenProjectIds:z.array(z.string().regex(/^[a-f0-9]{16}$/)).max(500),showBranch:z.boolean(),showModel:z.boolean(),showActivity:z.boolean(),showElapsed:z.boolean(),autoDetect:z.boolean(),launchAtStartup:z.boolean(),idleTimeoutMinutes:z.number().int().min(1).max(1440),manualActivity:z.enum(activities).nullable(),customStatus:z.string().max(64),automaticStatusTemplate:z.string().min(1).max(96),manualProject:z.string().max(64),discordClientId:z.string().regex(/^\d{0,24}$/),profiles:z.array(profile).max(8),activeProfileId:z.string().nullable(),presenceRules:z.array(presenceRule).max(64),projectStatusTemplates:z.array(projectTemplate).max(500),theme:z.enum(['midnight','violet','system']),accentColor:z.string().regex(/^#[a-fA-F0-9]{6}$/),systemIconBackground:z.string().regex(/^#[a-fA-F0-9]{6}$/),largeImageKey:assetKey,largeImageText:assetText,smallImageKey:assetKey,smallImageText:assetText});
let cached:Settings|null=null; const file=()=>path.join(app.getPath('userData'),'settings.json');
function withDefaultApplicationId(value:unknown):unknown {if(!value||typeof value!=='object')return value;const settings={...value} as Record<string,unknown>;if(!settings.discordClientId)settings.discordClientId=DISCORD_APPLICATION_ID;const profiles=Array.isArray(settings.profiles)?settings.profiles:[];if(!profiles.some(item=>item&&typeof item==='object'&&(item as {id?:unknown}).id==='default'))settings.profiles=[defaultProfile,...profiles];return settings;}
const profileControlledKeys:(keyof Settings)[]=['customStatus','manualActivity','privateProject','showProject','showBranch'];
export function normalizeProfileCustomization(current:Settings,patch:SettingsPatch):SettingsPatch {
  const requested=patch.showProject===true&&patch.privateProject===undefined?{...patch,privateProject:false}:patch;
  if(requested.activeProfileId!==undefined||!current.activeProfileId||!profileControlledKeys.some(key=>Object.prototype.hasOwnProperty.call(requested,key)))return requested;
  const profile=current.profiles.find(item=>item.id===current.activeProfileId);
  const visibilityChanged=Object.prototype.hasOwnProperty.call(requested,'showProject')||Object.prototype.hasOwnProperty.call(requested,'privateProject');
  const clearInheritedStatus=visibilityChanged&&profile?.customStatus===current.customStatus&&!Object.prototype.hasOwnProperty.call(requested,'customStatus');
  return{...requested,activeProfileId:null,...(clearInheritedStatus?{customStatus:''}:{})};
}
export function reconcileProfileState(settings:Settings):Settings {
  if(!settings.activeProfileId)return settings;
  const profile=settings.profiles.find(item=>item.id===settings.activeProfileId);
  if(!profile)return{...settings,activeProfileId:null};
  const changed=profileControlledKeys.some(key=>settings[key]!==profile[key as keyof typeof profile]);
  if(!changed)return settings;
  const visibilityChanged=settings.showProject!==profile.showProject||settings.privateProject!==profile.privateProject;
  return{...settings,activeProfileId:null,...(visibilityChanged&&settings.customStatus===profile.customStatus?{customStatus:''}:{})};
}
export function getSettings():Settings { if(cached)return cached;try{const stored=withDefaultApplicationId(JSON.parse(fs.readFileSync(file(),'utf8')));const parsed=schema.safeParse({...defaults,...stored as object});if(parsed.success){cached=reconcileProfileState(parsed.data);try{fs.writeFileSync(file(),JSON.stringify(cached,null,2),{encoding:'utf8',mode:0o600});}catch{}return cached;}}catch{}cached={...defaults};try{fs.mkdirSync(path.dirname(file()),{recursive:true});fs.writeFileSync(file(),JSON.stringify(cached,null,2),{encoding:'utf8',mode:0o600});}catch{}return cached; }
export function updateSettings(patch:SettingsPatch):Settings { const current=getSettings();const customized=normalizeProfileCustomization(current,patch);const normalized=customized.discordClientId===''?{...customized,discordClientId:DISCORD_APPLICATION_ID}:customized;const parsed=schema.safeParse({...current,...normalized});if(!parsed.success)throw new Error('Invalid settings');cached=parsed.data;fs.mkdirSync(path.dirname(file()),{recursive:true});fs.writeFileSync(file(),JSON.stringify(cached,null,2),{encoding:'utf8',mode:0o600});return cached; }
