#include "json_protocol.hpp"
#include <charconv>
#include <regex>
namespace {
std::optional<std::string> text(const std::string& s,const char* key){std::regex re(std::string("\\\"")+key+"\\\"\\s*:\\s*\\\"((?:\\\\.|[^\\\"])*)\\\"");std::smatch m;if(!std::regex_search(s,m,re))return {};std::string out;for(size_t i=0;i<m[1].str().size();++i){char c=m[1].str()[i];if(c=='\\'&&i+1<m[1].str().size()){char n=m[1].str()[++i];if(n=='n')out+='\n';else if(n=='r')out+='\r';else if(n=='t')out+='\t';else out+=n;}else out+=c;}return out;}
std::optional<uint64_t> number(const std::string&s,const char*key){std::regex re(std::string("\\\"")+key+"\\\"\\s*:\\s*([0-9]+)");std::smatch m;if(!std::regex_search(s,m,re))return {};uint64_t value{};auto v=m[1].str();auto result=std::from_chars(v.data(),v.data()+v.size(),value);return result.ec==std::errc{}?std::optional<uint64_t>(value):std::nullopt;}
bool valid_text(const std::optional<std::string>& value){return !value||(!value->empty()&&value->size()<=128);}
}
ParseResult parse_command(const std::string& line){if(line.empty()||line.front()!='{'||line.back()!='}')return {{}, "Malformed JSON"};auto type=text(line,"type");if(!type)return {{}, "Missing command type"};PresenceCommand c;c.type=*type;if(c.type=="clearPresence"||c.type=="shutdown")return {c,{}};if(c.type!="setPresence")return {{}, "Unknown command"};auto id=text(line,"applicationId"),name=text(line,"name"),details=text(line,"details");if(!id||id->empty()||id->size()>24||id->find_first_not_of("0123456789")!=std::string::npos)return {{}, "Invalid applicationId"};if(!name||*name!="Codex")return {{}, "Activity name must be Codex"};if(!details||!valid_text(details))return {{}, "Invalid details"};c.application_id=*id;c.name=*name;c.details=*details;c.state=text(line,"state");c.start_timestamp=number(line,"startTimestamp");c.large_image=text(line,"largeImage");c.large_text=text(line,"largeText");c.small_image=text(line,"smallImage");c.small_text=text(line,"smallText");if(!valid_text(c.state)||!valid_text(c.large_image)||!valid_text(c.large_text)||!valid_text(c.small_image)||!valid_text(c.small_text))return {{}, "Discord field exceeds 128 bytes"};return {c,{}};}
std::string json_escape(const std::string& value){std::string out;for(char c:value){if(c=='"'||c=='\\')out+='\\';if(c=='\n'){out+="\\n";continue;}out+=c;}return out;}
